# Generated by Django 2.2.4 on 2019-08-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0027_auto_20190824_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='summary',
            field=models.CharField(max_length=400),
        ),
    ]
