# Generated by Django 2.2.4 on 2019-08-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0029_auto_20190826_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='media/static/images'),
        ),
    ]
